name: online_groceries
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  fl_country_code_picker: ^0.0.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/img/


fonts:
  - family: Kanit
    fonts:
     - asset: font/Kanit-Regular.ttf
     - asset: font/Kanit-Italic.ttf
       style: italic
     - asset: font/Kanit-Bold.ttf
       weight: 700
     - asset: font/Kanit-Medium.ttf
       weight: 500
     - asset: font/Kanit-SemiBold.ttf
       weight: 600